#!/usr/bin/env node
// -*- javascript -*-

var firsts = require("./firsts");
var lift   = firsts.lift;
var maybe  = firsts.maybe;

subreddits = process.argv.slice(2);

var start = new Date();
firsts.downloadAll(subreddits, function (firsts){
    var end = new Date();
    var elapsed = (end - start) / 1000
    console.log(
	"" + elapsed + "s"
    )
});
