#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable

main([CountStr|Subreddits]) ->
    application:start(inets),
    Count = list_to_integer(CountStr),
    lists:foreach(fun(_) ->
			  firsts:main(Subreddits)
		  end,
		  lists:seq(1, Count)).

